Added new service account for PRP to access PLR
bcgov/moh-keycloak-client-configurations pull request #102
Opened 2023-01-10 20:31 UTC by nathanielcx

2023-01-10 20:43 UTC, sharpedavid requested changes
You need to reference the new client module in the parent main file, /moh-keycloak-client-configurations/keycloak-dev/realms/moh_applications/main.tf

2023-01-10 23:50 UTC, sharpedavid commented on keycloak-dev/realms/moh_applications/prp-system/main.tf
> +  description                         = "The Provider and Location Registry (PLR) is a standards-based repository of core provider data supplied by authorized sources, and available to authorized con
Wrong description.

Who is this service account for? We should name the client and module similar to PLR-SHOPPERS, I think... What would that mean then. PLR-PRP-SERVICE-ACCOUNT?

2023-01-11 15:18 UTC, nathanielcx commented on keycloak-dev/realms/moh_applications/prp-system/main.tf
> +  description                         = "The Provider and Location Registry (PLR) is a standards-based repository of core provider data supplied by authorized sources, and available to authorized con
I actually think PLR-PRP would follow the "convention" more closely now that I've given it some thought. They are likely going to use it the exact same way as the shoppers client, so maybe any clients like this should just be listed as PLR-XXXX

2023-01-11 18:47 UTC, sharpedavid approved these changes

2023-01-11 18:52 UTC, merged