Add LICENCE-STATUS client.
bcgov/moh-keycloak-client-configurations pull request #110
Opened 2023-01-16 05:29 UTC by sharpedavid

Add LICENCE-STATUS to UMS. Allow PIPD to manage LICENCE-STATUS and DMFT-WEBAPP roles.

2023-01-16 05:52 UTC, sharpedavid commented on keycloak-dev/realms/moh_applications/dmft-webapp/main.tf
> +#}
I was getting some errors trying to add the scope mappings. I suspect the roles need to exist before I can use them here. I will finish this PR, and then submit another with this un-commented out.

2023-01-16 05:54 UTC, sharpedavid commented on keycloak-dev/realms/moh_applications/pidp-service/main.tf
> +    "USER-MANAGEMENT-SERVICE/view-client-sat-eforms"     = var.USER-MANAGEMENT-SERVICE.ROLES["view-client-sat-eforms"].id,
The change in code formatting might make this look like I changed the entire block. Use the gear icon at the top to ignore white space changes. I gave the PIPD service account UMS roles on DMFT-WEBAPP and LICENCE-STATUS.

2023-01-16 17:47 UTC, ahoplock commented on keycloak-dev/realms/moh_applications/user-management-service/main.tf
> +    "view-client-licence-status" = {
We've been ordering these roles in alphabetical order but I get why it makes sense lumping it together with DMFT.

2023-01-16 17:49 UTC, ahoplock commented on keycloak-dev/realms/moh_applications/pidp-service/main.tf
> +    "USER-MANAGEMENT-SERVICE/view-client-licence-status" = {
See comment below about alphabetical order.

2023-01-16 17:50 UTC, ahoplock commented on keycloak-dev/realms/moh_applications/pidp-service/main.tf
> +    "USER-MANAGEMENT-SERVICE/view-client-licence-status" = var.USER-MANAGEMENT-SERVICE.ROLES["view-client-licence-status"].id,
See comment below about alphabetical order.

2023-01-16 17:54 UTC, ahoplock requested changes
Couple minor things regarding ordering...feel free to disregard if I'm being too nitpick-y here.

2023-01-17 16:57 UTC, ahoplock approved these changes
Reviewed and approved.

2023-01-17 18:56 UTC, merged