Plr qa clients
bcgov/moh-keycloak-client-configurations pull request #146
Opened 2023-02-16 19:20 UTC by nathanielcx

2023-02-16 20:47 UTC, filipflorek requested changes
I believe `full_scope_allowed` should be set to false in all clients

2023-02-17 19:48 UTC, filipflorek approved these changes

2023-02-17 19:51 UTC, sharpedavid commented on keycloak-test/realms/moh_applications/plr-qa-secondary-source/main.tf
> +  description                         = "The Provider and Location Registry (PLR) is a standards-based repository of core provider data supplied by authorized sources. This client will be used to gen
It doesn't look look like the description matches the actual role assigned. It might be better to just delete the descriptions. Out of date or incorrect documentation is worse than no documentation. Or fix it.

2023-02-17 19:53 UTC, sharpedavid commented on keycloak-test/realms/moh_applications/plr-qa-dsr-user/main.tf
> +  description                         = "The Provider and Location Registry (PLR) is a standards-based repository of core provider data supplied by authorized sources. This client will be used to gen
I don't think this matches the actual roles assigned. See other comment.

2023-02-17 19:58 UTC, sharpedavid requested changes
Just the descriptions to be fixed.

2023-02-17 20:04 UTC, filipflorek commented on keycloak-test/realms/moh_applications/plr-qa-secondary-source/main.tf
> +  description                         = "The Provider and Location Registry (PLR) is a standards-based repository of core provider data supplied by authorized sources. This client will be used to gen
Swapped the role names in corresponding clients.

2023-02-17 20:42 UTC, sharpedavid approved these changes

2023-02-17 20:43 UTC, merged