AM-8688-simplify-ums-client
bcgov/moh-keycloak-client-configurations pull request #199
Opened 2023-04-06 21:42 UTC by alex-tremblay-cgi

2023-04-11 20:58 UTC, filipflorek requested changes
I added some comments directly to files. In order to create a client, you need to create it's config (as you did) and register it as a module in keycloak-dev/realms/moh_applications/main.tf
file. I can go over those couple things with you tomorrow!

2023-04-11 20:58 UTC, filipflorek commented on keycloak-dev/realms/moh_applications/user-management-service-integration-tests/versions.tf
> +      version = ">= 3.0.0"
We've just update mrparkers version. If you could please rebase the branch and change version here to >= 4.2.0

2023-04-11 20:58 UTC, filipflorek commented on keycloak-dev/realms/moh_applications/user-management-service-integration-tests/main.tf
> +    "USER-MANAGEMENT-SERVICE/create-user"         = var.ORGANIZATIONS-API.ROLES["create-user"].id,
I'm not sure if I understand this here, shouldn't it be USER-MANAGEMENT-SERVICE instead of ORGANIZATIONS-API? It's UMS who owns those roles.

2023-04-11 20:58 UTC, filipflorek commented on keycloak-dev/realms/moh_applications/user-management-service-integration-tests/variables.tf
I think you need to declare a variable here, that you use later in `keycloak-dev/realms/moh_applications/user-management-service-integration-tests/main.tf` file, in scope mappings part of it `var.ORGANIZATIONS-API.ROLES["view-groups"].id` You can find some examples of how it should be set up in existing configuration.

2023-04-12 16:47 UTC, alex-tremblay-cgi commented on keycloak-dev/realms/moh_applications/user-management-service-integration-tests/main.tf
> +    "USER-MANAGEMENT-SERVICE/create-user"         = var.ORGANIZATIONS-API.ROLES["create-user"].id,
Yes my error

2023-04-21 19:09 UTC, filipflorek requested changes

2023-04-21 19:09 UTC, filipflorek commented on keycloak-dev/realms/moh_applications/user-management-service-integration-tests/versions.tf
> +      version = ">= 3.0.0"
If you can change this please, just for consistency!

```suggestion
      version = "3.9.1"
```

2023-04-21 19:10 UTC, filipflorek commented
The client setup and cleanup looks good!

2023-05-02 22:32 UTC, filipflorek approved these changes

2023-05-02 22:34 UTC, merged