manage PIDP WEBAPP and PIDP SERVICE in DEV
bcgov/moh-keycloak-client-configurations pull request #20
Opened 2022-07-11 23:55 UTC by vangeliq

2022-07-12 00:01 UTC, vangeliq commented
added 2 modules:
- service account roles:  tracks the service account's roles. 
- scope mappings: tracks the realm & client level scope mappings

2022-07-12 00:01 UTC, sharpedavid commented on keycloak-dev/realms/moh-applications/pidp-service/pidp-service.tf
> +			"client_id" = "2ddc7173-34f3-41ff-9beb-66c7802717ce",
This is the UMS client ID, should we try to `output` it? This would save some manual work for each environment.

2022-07-12 00:03 UTC, sharpedavid commented on keycloak-dev/realms/moh-applications/pidp-webapp/pidp-webapp.tf
> +		"account/view-profile" = "22f2f067-d74a-4108-bf1a-eb6bffd71736",
Is there a way to `output` these in PIDP-SERVICE so they can be reused? Again it would just save a lot of manual configuration for each ENV. 

This also prevents us from easily recreating the clients in a new environment because the IDs aren't something we control.

2022-07-12 00:05 UTC, vangeliq commented on keycloak-dev/realms/moh-applications/pidp-service/pidp-service.tf
> +			"client_id" = "2ddc7173-34f3-41ff-9beb-66c7802717ce",
that's a good point, I'll try doing that

2022-07-12 21:16 UTC, sharpedavid commented on keycloak-dev/realms/moh-applications/pidp-webapp/pidp-webapp.tf
> +		"account/view-profile" = "22f2f067-d74a-4108-bf1a-eb6bffd71736",
Sorry I forgot to mention, but it doesn't need this client. That was in the defaults, but it's not using it AFAIK.

2022-07-13 20:25 UTC, sharpedavid requested changes

2022-07-13 20:25 UTC, sharpedavid commented on keycloak-dev/realms/moh-applications/user-management-service/user-management-service.tf
> +			"role_id" = "view-client-mspdirect-service"
Not exactly code review feedback, but just are reminder that we're going to remove User Management Service's roles on itself. That's what these are: we define that the UMS service account has permission to call UMS. We did this for integration tests, but we should really have a dedicated client for integration tests to avoid confusion.

2022-07-14 18:19 UTC, vangeliq commented on keycloak-dev/realms/moh-applications/pidp-service/pidp-service.tf
> +			composite_roles = []
I think I'm going to delete the composite roles, but keeping the description. some roles have descriptions (but none of the roles we manage have composite roles). setting up the key values to optional is still an experimental feature.

2022-07-14 23:53 UTC, sharpedavid submitted a review, later dismissed

2022-07-14 23:57 UTC, sharpedavid approved these changes

2022-07-20 19:32 UTC, closed without merging