Add hcap service to prod
bcgov/moh-keycloak-client-configurations pull request #207
Opened 2023-04-17 19:43 UTC by alex-tremblay-cgi

2023-04-19 17:05 UTC, filipflorek approved these changes

2023-04-20 16:23 UTC, filipflorek submitted a review, later dismissed

2023-04-20 19:16 UTC, sharpedavid requested changes

2023-04-20 19:16 UTC, sharpedavid commented on keycloak-prod/realms/moh_applications/user-management-service/main.tf
> +      "name" = "view-client-hcap-fe"
Open a second PR to give PIDP-SERVICE this role as a service account role.

2023-04-20 19:16 UTC, sharpedavid commented on keycloak-prod/realms/moh_applications/hcap-fe/main.tf
> +  valid_redirect_uris                 = ["http://localhost:4000"]
Set the following:

![image](https://user-images.githubusercontent.com/1767127/233464874-c53b08f8-ff54-4b6e-a327-4b26bcf3f4e6.png)

```
https://hcapemployers.gov.bc.ca

/*
https://www.hcapemployers.gov.bc.ca/*
https://www.hcapparticipants.gov.bc.ca/*
https://hcapparticipants.gov.bc.ca/*
https://hcapemployers.gov.bc.ca/*

https://hcapemployers.gov.bc.ca
```

2023-04-21 19:11 UTC, sharpedavid approved these changes

2023-04-21 19:11 UTC, merged