Add dev client for PLR WAVA scan
bcgov/moh-keycloak-client-configurations pull request #372
Opened 2023-11-03 23:21 UTC by daveb-hni

### Changes being made

Adding new client in dev

### Context

A client is required for PLR to run a WAVA scan

### Quality Check

- [ ] Client has Name and Description defined.
- [ ] Full Scope Allowed is disabled.
- [ ] Direct Access Grants Enabled is disabled.
- [ ] Valid Redirect URIs are properly defined, or explanation for `*` (allow all) is provided.
- [ ] Web Origins are set to `+` instead of `*` to restrict the CORS origins.
- [ ] Client Scopes are not assigned to client, or explanation for doing so is provided. [^1]
- [ ] Client module and all references are defined in clients.tf in realm root folder. Same rule applies to other resources, like groups and realm roles.
- [ ] Terraform plan contains only my changes, or other developers are aware that their manual changes can be overridden. [^2]
- [ ] [CMDB](https://cmdb.hlth.gov.bc.ca/cmdbuildProd/ui/#classes/Application/cards) is updated, if applicable.

[^1]: Data transparency. Does the client you are creating have the permissions to pass/access all the Client Scope attributes in the token? For example `profile` scope includes user birthdate, which is used by BCSC, but other applications shouldn't necessarily have access to it.
[^2]:
    Keep in mind that sometimes Keycloak automatically adds properties to newly created resources. `terraform plan` will show them as changes made outside of Terraform. As long as those attributes are empty and do not interfere with existing configuration, they can be ignored. Here is example of one:
    ![Terraform](https://user-images.githubusercontent.com/52381251/236051457-cdf91ff2-adc1-4ec0-b648-bfbcd7c55198.png)

2023-11-03 23:59 UTC, filipflorek approved these changes

2023-11-06 23:54 UTC, filipflorek requested changes

2023-11-06 23:54 UTC, filipflorek commented on keycloak-test/realms/moh_applications/clients/plr-wava/variables.tf
I think a PLR_REV should be defined as a variable here - it's later referenced in plr-wava/main.tf file
`variable "PLR_REV" {}`

2023-11-06 23:54 UTC, filipflorek commented on keycloak-test/realms/moh_applications/clients.tf
> +  source = "./clients/plr-wava"
PLR-WAVA module references PLR_REV, so it needs to be declared here as well.
`PLR_REV  = module.PLR_REV`

2023-11-06 23:54 UTC, filipflorek commented on keycloak-test/realms/moh_applications/clients/plr-wava/main.tf
> +    "PLR_REV/CONSUMER"  = var.PLR_REV.ROLES["PRIMARY_SOURCE"].id
Here the reference should be `PLR_REV/PRIMARY_SOURCE` instead of `PLR_REV/CONSUMER`

2023-11-06 23:59 UTC, daveb-hni commented on keycloak-test/realms/moh_applications/clients/plr-wava/variables.tf
added

2023-11-06 23:59 UTC, daveb-hni commented on keycloak-test/realms/moh_applications/clients.tf
> +  source = "./clients/plr-wava"
added

2023-11-07 00:00 UTC, daveb-hni commented on keycloak-test/realms/moh_applications/clients/plr-wava/main.tf
> +    "PLR_REV/CONSUMER"  = var.PLR_REV.ROLES["PRIMARY_SOURCE"].id
fixed

2023-11-07 02:08 UTC, filipflorek approved these changes

2023-11-07 05:43 UTC, merged