create phlat-web client, update phlat service account and management groups
bcgov/moh-keycloak-client-configurations pull request #469
Opened 2024-02-28 22:37 UTC by filipflorek

### Changes being made

Add PHLAT-WEB client. Update PHLAT client. Update UMS view-client-* roles and user management groups

### Context

PHLAT-WEB is a public client used to authenticate via Vue.js app. PHLAT is now just a service account used to call PLR API.

### Quality Check

- [ ] Client has Name and Description defined.
- [ ] Full Scope Allowed is disabled.
- [ ] Direct Access Grants Enabled is disabled.
- [ ] Valid Redirect URIs are properly defined, or explanation for `*` (allow all) is provided.
- [ ] Web Origins are set to `+` instead of `*` to restrict the CORS origins.
- [ ] Client Scopes are not assigned to client, or explanation for doing so is provided. [^1]
- [ ] Client module and all references are defined in clients.tf in realm root folder. Same rule applies to other resources, like groups and realm roles.
- [ ] Terraform plan contains only my changes, or other developers are aware that their manual changes can be overridden. [^2]
- [ ] [CMDB](https://cmdb.hlth.gov.bc.ca/cmdbuildProd/ui/#classes/Application/cards) is updated, if applicable.
- [ ] When updating `composite roles` (eg. Realm roles) and `scope mapping` resources, remember to re-run the apply. [^3]

[^1]: Data transparency. Does the client you are creating have the permissions to pass/access all the Client Scope attributes in the token? For example `profile` scope includes user birthdate, which is used by BCSC, but other applications shouldn't necessarily have access to it.
[^2]:
    Keep in mind that sometimes Keycloak automatically adds properties to newly created resources. `terraform plan` will show them as changes made outside of Terraform. As long as those attributes are empty and do not interfere with existing configuration, they can be ignored. Here is example of one:
    ![Terraform](https://user-images.githubusercontent.com/52381251/236051457-cdf91ff2-adc1-4ec0-b648-bfbcd7c55198.png)

[^3]: Due to the terraform provider bug, updating/deleting one entry within the resource deletes all of them. Re-running the `apply` action will result in restoring the configuration to the desired state. Keep in mind, that `composite role` deletion will show up on the `terraform plan` output, on contrary to `scope mapping`.

2024-02-28 23:26 UTC, sharpedavid requested changes

2024-02-28 23:26 UTC, sharpedavid commented on keycloak-test/realms/moh_applications/clients/phlat-web/main.tf
> +  claim_name                  = "roles"
Just a heads-up that not everyone needs this. The roles will be included in "resource_access > client_id > roles" or some claim like that. We were adding mappers like this for Salesforces and Payara, which seems less flexible in token structure.

2024-02-28 23:26 UTC, sharpedavid commented on keycloak-test/realms/moh_applications/clients/phlat/main.tf
>    client_id                           = "PHLAT"
We haven't been entirely consistent, but we've often appended `-SERVICE` to clients used exclusively as service accounts.

2024-02-28 23:27 UTC, sharpedavid commented
Also please update CMDB.

2024-02-29 00:40 UTC, filipflorek commented on keycloak-test/realms/moh_applications/clients/phlat/main.tf
>    client_id                           = "PHLAT"
Thanks, my reasoning was that I don't want the client id an secret to change. But since they're at the beginning of the integration I'll switch that to be consistent with our system

2024-02-29 00:43 UTC, filipflorek commented on keycloak-test/realms/moh_applications/clients/phlat-web/main.tf
> +  claim_name                  = "roles"
Right, I told them (PHLAT team) about this option and added it so that the roles claim structure is more simple. But now that I say it out loud it does not seem as a good reason. Should I delete this?

2024-02-29 17:25 UTC, filipflorek commented
> Also please update CMDB.

CMDB updated

2024-02-29 19:20 UTC, sharpedavid commented on keycloak-test/realms/moh_applications/clients/phlat-web/main.tf
> +  claim_name                  = "roles"
It gets trickier to check if tokens are safe, but it's not a big problem. If we give out a token that says `roles: ['ADMIN']`, it's hard for an app to know who is supposed to be the ADMIN. A bad user or app could use this token to pretend to have ADMIN rights in another app. If the other app checks the `aud` (audience) claim, it might spot the problem. In the future, we should either stop doing this or make sure the claim name includes the client ID, which helps make sure the token is used correctly.

2024-02-29 19:21 UTC, sharpedavid approved these changes

2024-02-29 19:23 UTC, merged