Configure idp restriction module for plr
bcgov/moh-keycloak-client-configurations pull request #603
Opened 2024-09-10 22:13 UTC by filipflorek

### Changes being made

Override browser flow and theme for PLR client on DEV so that it uses the IDP restriction module.
Update payara-client module to allow overriding authentication(browser) flows.

### Context

IDP Restriction module work.
AuthenticationFlowBindingOverrides is an object, so unlike with primitive types a simple conditional expression cannot be used. Empty object would be created for each payara client that doesn't override authentication flow.
Instead, the solution uses `dynamic block` to conditionally assign this resource property. This ensures that only clients with `authentication_flow_binding_overrides` variable will undergo configuration change,

If `var.authentication_flow_binding_overrides` is not null, [1] triggers the dynamic block to create a single authentication_flow_binding_overrides block. [1] represents a list with single element.
If `var.authentication_flow_binding_overrides` is null, the empty list [] ensures that the dynamic block is not rendered at all.

I wanted to make configuration look the same, regardless if it's client from payara or a plain oidc client. That's why `variable "authentication_flow_binding_overrides"` is a map/object, instead of primitive type (for example just `browser_id` could be passed as a variable)

https://developer.hashicorp.com/terraform/language/v1.3.x/expressions/dynamic-blocks
https://developer.hashicorp.com/terraform/language/v1.3.x/expressions/conditionals

### Quality Check

- [ ] Terraform plan contains only my changes, or other developers are aware that their manual changes can be overridden.

2024-09-10 22:45 UTC, sharpedavid commented on keycloak-dev/realms/moh_applications/clients/plr/main.tf
> +    browser_id = "9caca0f9-1c0c-4def-85c6-637d1c8a4d24"
I'm not sure if we'll use this implementation or not, but if we do, see if you can declare this as a named constant somewhere.

```hcl
locals {
  browser-idp-restriction = "9caca0f9-1c0c-4def-85c6-637d1c8a4d24"
}
```

Or something like that. I'm not an expert on this stuff.

2024-09-10 22:49 UTC, sharpedavid commented on keycloak-dev/realms/moh_applications/clients/plr/main.tf
> +  authentication_flow_binding_overrides = {
Is it actually necessary to use a map for this? We can't use something like this?

`authentication_flow_binding_override_browser_id = "9caca0f9-1c0c-4def-85c6-637d1c8a4d24"`

Will there ever be more than one?

2024-09-10 22:57 UTC, sharpedavid commented on modules/payara-client/main.tf
> +  }
If this is the implementation we choose we'll want a little documentation here explaining how it works. We're never going to have many (any) Terraform experts. 

e.g. What does "dynamic" mean, how does `[1]` work, and why are we using `lookup` instead of a single literal value?

2024-09-10 22:59 UTC, sharpedavid requested changes
I have questions, see my previous comments.

2024-09-10 23:13 UTC, filipflorek commented on keycloak-dev/realms/moh_applications/clients/plr/main.tf
> +  authentication_flow_binding_overrides = {
Looking at the documentation, there are two optional values - you could override browser flow or direct grant flow. It's a resource from mrparkers provider so not much we can do here.
https://registry.terraform.io/providers/sharekey/keycloak/latest/docs/resources/openid_client#authentication_flow_binding_overrides

What we could do though, is something like that (in the module file):
```
authentication_flow_binding_overrides {
         browser_id = var.browser_id
    }
  }
```
where browser_id is a variable passed from a specific client. This would make config easier to read. The downside of this approach is that empty `authentication_flow_binding_overrides` object would be created for each payara client and that config for payara clients would be different than for plain oidc. 

In payara you would just put:
browser_id = "my-flow-id"
But in OIDC client you would have to specify the whole map:
```
authentication_flow_binding_overrides {
         browser_id = "my-flow-id"
    }
  }
```

2024-09-10 23:46 UTC, sharpedavid commented on keycloak-dev/realms/moh_applications/clients/plr/main.tf
> +  authentication_flow_binding_overrides = {
Couldn't you still use a dynamic block?

```hcl
// in the PLR module:
authentication_flow_binding_override_browser_id = "9caca0f9-1c0c-4def-85c6-637d1c8a4d24"


// in the Payara module:
dynamic "authentication_flow_binding_overrides" {
  for_each = var.authentication_flow_binding_override_browser_id != null ? [1] : []
  content {
    browser_id = var.authentication_flow_binding_override_browser_id
  }
}
```

This avoids the unnecessary "map" construct while still not creating a bunch of empty objects unintentionally on all Payara clients.

2024-09-12 22:33 UTC, filipflorek commented on keycloak-dev/realms/moh_applications/clients/plr/main.tf
> +  authentication_flow_binding_overrides = {
Right, I'll do that. The only thing I had against it is that it makes config look different between plain OIDC vs Payara clients. But we define roles in different way for both those clients, so my argument isn't the best

2024-09-12 23:30 UTC, sharpedavid approved these changes

2024-09-12 23:39 UTC, sharpedavid approved these changes

2024-09-12 23:42 UTC, merged